// NikVolt katalog modula.
// Ovaj fajl slobodno uredjujes rucno. Posle izmene uradi refresh aplikacije.
// Za Vercel/GitHub: sacuvaj izmenu, commit i push.
//
// Primer novog modula:
// {kod:'9999', naziv:'Nova uticnica', serija:'MODE', kat:'uticnica', vel:2, opis:'16A 250V~ 2M'},
//
// Polja modula:
// kod    - sifra artikla bez .0
// naziv  - naziv koji se prikazuje u aplikaciji
// serija - MODE ili EXP
// kat    - sklopka, uticnica, usb, data, tel, antena, audio, hdmi, dimmer, detektor, ostalo
// vel    - koliko mesta zauzima u dozni: 1, 2, 4...
// opis   - kratak opis

window.NIKVOLT_MODULES = {
  MODE: [
  {kod:'655',   naziv:'Sklopka jednopolna',                  serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M'},
  {kod:'657',   naziv:'Sklopka naizmenična',                 serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M'},
  {kod:'658',   naziv:'Sklopka ukrsna',                      serija:'MODE', kat:'sklopka',  vel:2, opis:'10AX 250V~ 2M'},
  {kod:'6552',  naziv:'Sklopka jednopolna 2M',               serija:'MODE', kat:'sklopka',  vel:2, opis:'10AX 250V~ 2M'},
  {kod:'6572',  naziv:'Sklopka naizmenična 2M',              serija:'MODE', kat:'sklopka',  vel:2, opis:'10AX 250V~ 2M'},
  {kod:'6554',  naziv:'Sklopka dvopolna 2M',                 serija:'MODE', kat:'sklopka',  vel:2, opis:'10AX 250V~ 2M'},
  {kod:'675',   naziv:'Sklopka jednopolna + indikacija',     serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M, ind. isklj.'},
  {kod:'6752',  naziv:'Sklopka jednopolna ind. uklj.',       serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M, ind. uklj.'},
  {kod:'677',   naziv:'Sklopka naizmenična + indikacija',    serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M'},
  {kod:'678',   naziv:'Sklopka ukrsna + indikacija 2M',      serija:'MODE', kat:'sklopka',  vel:2, opis:'10AX 250V~ 2M'},
  {kod:'6581',  naziv:'Sklopka jednopolna 16A',              serija:'MODE', kat:'sklopka',  vel:1, opis:'16AX 250V~ 1M'},
  {kod:'6582',  naziv:'Sklopka naizmenična 16A',             serija:'MODE', kat:'sklopka',  vel:1, opis:'16AX 250V~ 1M'},
  {kod:'6590',  naziv:'Sklopka ukrsna 16A 2M',               serija:'MODE', kat:'sklopka',  vel:2, opis:'16AX 250V~ 2M'},
  {kod:'6600',  naziv:'Sklopka dvopolna 16A 2M',             serija:'MODE', kat:'sklopka',  vel:2, opis:'16AX 250V~ 2M'},
  {kod:'6541',  naziv:'Taster jednopolni 1M',                serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M'},
  {kod:'6542',  naziv:'Taster naizmenični 1M',               serija:'MODE', kat:'sklopka',  vel:1, opis:'10AX 250V~ 1M'},
  {kod:'652',   naziv:'Utičnica CEI (italiana)',             serija:'MODE', kat:'utičnica', vel:1, opis:'10A 250V~ 1M'},
  {kod:'654',   naziv:'Utičnica 16A francoski',              serija:'MODE', kat:'utičnica', vel:2, opis:'16A 250V~ 2M'},
  {kod:'6540',  naziv:'Utičnica 16A sa zaštitom',            serija:'MODE', kat:'utičnica', vel:2, opis:'16A 250V~ 2M, sa zaštitom od dodira'},
  {kod:'66512', naziv:'Sklop 2× utičnica (premoštene)',      serija:'MODE', kat:'utičnica', vel:4, opis:'16A 250V~ 2×2M'},
  {kod:'66513', naziv:'Sklop 3× utičnica (premoštene)',      serija:'MODE', kat:'utičnica', vel:6, opis:'16A 250V~ 3×2M'},
  {kod:'6671',  naziv:'Dimmer sijalice/halogene',            serija:'MODE', kat:'dimmer',   vel:1, opis:'230V~ 40-300VA 1M'},
  {kod:'6672',  naziv:'Dimmer sa sklopkom',                  serija:'MODE', kat:'dimmer',   vel:1, opis:'230V~ 40-300VA 1M'},
  {kod:'6674',  naziv:'Dimmer LED (univ. taster)',           serija:'MODE', kat:'dimmer',   vel:1, opis:'Elektronski 1M'},
  {kod:'6675',  naziv:'Dimmer elektronski LED 2M',           serija:'MODE', kat:'dimmer',   vel:2, opis:'40-300VA 2M'},
  {kod:'6692',  naziv:'Regulator brzine ventilatora 2M',     serija:'MODE', kat:'dimmer',   vel:2, opis:'230V~ 2M'},
  {kod:'6673',  naziv:'IC detektor pokreta 500W 2M',         serija:'MODE', kat:'detektor', vel:2, opis:'Relejni max 500W, 230V~ 2M'},
  {kod:'6676',  naziv:'IC detektor pokreta 1M',              serija:'MODE', kat:'detektor', vel:1, opis:'Ugao 110°, domet 7m, 1M'},
  {kod:'6629',  naziv:'USB punjač 2,1A (tip A)',             serija:'MODE', kat:'usb',      vel:1, opis:'2,1A 5V~ 1M'},
  {kod:'6626',  naziv:'USB tip C punjač 3A',                 serija:'MODE', kat:'usb',      vel:1, opis:'3A/5V~ 1M'},
  {kod:'6615',  naziv:'HDMI utičnica',                       serija:'MODE', kat:'hdmi',     vel:1, opis:'HDMI socket 1M'},
  {kod:'661',   naziv:'Telefon RJ12 6/2',                    serija:'MODE', kat:'tel',      vel:1, opis:'RJ12 6/2 1M'},
  {kod:'663',   naziv:'Telefon RJ12 6/4',                    serija:'MODE', kat:'tel',      vel:1, opis:'RJ12 6/4 1M'},
  {kod:'6631',  naziv:'Telefon Keystone RJ12 Cat3',          serija:'MODE', kat:'tel',      vel:1, opis:'ISDN, Toolless 1M'},
  {kod:'664',   naziv:'RJ45 Keystone Cat5e UTP',             serija:'MODE', kat:'data',     vel:1, opis:'Keystone RJ45 Cat5e UTP 1M'},
  {kod:'664S',  naziv:'RJ45 Keystone Cat5e FTP',             serija:'MODE', kat:'data',     vel:1, opis:'Keystone RJ45 Cat5e FTP 1M'},
  {kod:'665',   naziv:'RJ45 Keystone Cat6 UTP',              serija:'MODE', kat:'data',     vel:1, opis:'Keystone RJ45 Cat6 UTP 1M'},
  {kod:'665S',  naziv:'RJ45 Keystone Cat6 FTP',              serija:'MODE', kat:'data',     vel:1, opis:'Keystone RJ45 Cat6 FTP 1M'},
  {kod:'666',   naziv:'RJ45 ELine Cat6 UTP',                 serija:'MODE', kat:'data',     vel:1, opis:'ELine RJ45 Cat6 UTP 1M'},
  {kod:'666S',  naziv:'RJ45 ELine Cat6 STP',                 serija:'MODE', kat:'data',     vel:1, opis:'ELine RJ45 Cat6 STP 1M'},
  {kod:'666M',  naziv:'RJ45 ELine EC7 Cat7 STP',             serija:'MODE', kat:'data',     vel:1, opis:'ELine EC7 Cat7 STP 1M'},
  {kod:'6519',  naziv:'Keystone nosač 1M',                   serija:'MODE', kat:'data',     vel:1, opis:'22,2mm, Keystone holder'},
  {kod:'6621',  naziv:'Antenska TV IEC M/F',                 serija:'MODE', kat:'antena',   vel:1, opis:'TV aerial IEC M/F 1M'},
  {kod:'6622',  naziv:'Antenska FM IEC F/F',                 serija:'MODE', kat:'antena',   vel:1, opis:'FM aerial IEC F/F 1M'},
  {kod:'6623',  naziv:'Antenska TV završna 5dB',             serija:'MODE', kat:'antena',   vel:1, opis:'End-line 5dB IEC 1M'},
  {kod:'6624',  naziv:'Antenska TV prolazna 10dB',           serija:'MODE', kat:'antena',   vel:1, opis:'Throughpass 10dB IEC 1M'},
  {kod:'6625',  naziv:'SAT antenska F/F',                    serija:'MODE', kat:'antena',   vel:1, opis:'TV aerial F/F, SAT 1M'},
  {kod:'6628',  naziv:'Audio/video BNC/BNC',                 serija:'MODE', kat:'audio',    vel:1, opis:'BNC/BNC 1M'},
  {kod:'6627',  naziv:'Audio 2×RCA',                         serija:'MODE', kat:'audio',    vel:1, opis:'Audio socket 2×RCA 1M'},
  {kod:'6500',  naziv:'Slijepi modul',                       serija:'MODE', kat:'ostalo',   vel:1, opis:'Blank 1M'},
],

  EXP: [
  {kod:'73104', naziv:'Sklopka jednopolna EXP 1M',           serija:'EXP',  kat:'sklopka',  vel:1, opis:'1 pole switch EXP 1M'},
  {kod:'73105', naziv:'Sklopka naizmenična EXP 1M',          serija:'EXP',  kat:'sklopka',  vel:1, opis:'2 way switch EXP 1M'},
  {kod:'73106', naziv:'Sklopka ukrsna EXP 1M',               serija:'EXP',  kat:'sklopka',  vel:1, opis:'Intermediate EXP 1M'},
  {kod:'73101', naziv:'Taster EXP 1M',                       serija:'EXP',  kat:'sklopka',  vel:1, opis:'Button EXP 1M, 22,2mm'},
  {kod:'73304', naziv:'Sklopka jednopolna EXP 2M',           serija:'EXP',  kat:'sklopka',  vel:2, opis:'1 pole switch EXP 2M'},
  {kod:'73305', naziv:'Sklopka naizmenična EXP 2M',          serija:'EXP',  kat:'sklopka',  vel:2, opis:'2 way switch EXP 2M'},
  {kod:'73306', naziv:'Sklopka ukrsna EXP 2M',               serija:'EXP',  kat:'sklopka',  vel:2, opis:'Intermediate EXP 2M'},
  {kod:'73301', naziv:'Taster EXP 2M',                       serija:'EXP',  kat:'sklopka',  vel:2, opis:'Button EXP 2M, 44,4mm'},
  {kod:'72202', naziv:'Dimmer sijalice EXP',                 serija:'EXP',  kat:'dimmer',   vel:1, opis:'230V~ 1M EXP'},
  {kod:'72204', naziv:'Dimmer sa sklopkom EXP',              serija:'EXP',  kat:'dimmer',   vel:1, opis:'230V~ 1M EXP'},
  {kod:'72205', naziv:'Dimmer LED EXP',                      serija:'EXP',  kat:'dimmer',   vel:1, opis:'Univ. taster elektronski 1M'},
  {kod:'72208', naziv:'Dimmer LED sa sklopkom EXP',          serija:'EXP',  kat:'dimmer',   vel:1, opis:'230V~ 1M EXP'},
  {kod:'72117', naziv:'Dimmer elektronski EXP 1M',           serija:'EXP',  kat:'dimmer',   vel:1, opis:'EXP 1M'},
  {kod:'72203', naziv:'IC detektor pokreta 500W EXP 2M',     serija:'EXP',  kat:'detektor', vel:2, opis:'Max 500W, 2M EXP'},
  {kod:'72209', naziv:'IC detektor pokreta EXP 1M',          serija:'EXP',  kat:'detektor', vel:1, opis:'Ugao 110°, domet 7m, 1M'},
  {kod:'74121', naziv:'Utičnica CEI (italiana) EXP',         serija:'EXP',  kat:'utičnica', vel:1, opis:'10A 250V~ 1M CEI 23-50/P11'},
  {kod:'74151', naziv:'Utičnica 16A francoski EXP',          serija:'EXP',  kat:'utičnica', vel:2, opis:'16A 250V~ 2M IEC 60884-1'},
  {kod:'74152', naziv:'Utičnica 16A sa zaštitom EXP',        serija:'EXP',  kat:'utičnica', vel:2, opis:'16A 250V~ 2M, zaštita od dodira'},
  {kod:'74162', naziv:'Sklop 2× utičnica EXP',               serija:'EXP',  kat:'utičnica', vel:4, opis:'16A 250V~ 2×2M premoštene'},
  {kod:'74163', naziv:'Sklop 3× utičnica EXP',               serija:'EXP',  kat:'utičnica', vel:6, opis:'16A 250V~ 3×2M premoštene'},
  {kod:'74289', naziv:'USB punjač 2,1A EXP 1M',              serija:'EXP',  kat:'usb',      vel:1, opis:'USB charger 2,1A 5V~ 1M'},
  {kod:'74283', naziv:'USB punjač 2,1A EXP 2M',              serija:'EXP',  kat:'usb',      vel:2, opis:'USB charger 2,1A 5V~ 2M'},
  {kod:'74284', naziv:'USB utičnica (data) EXP',             serija:'EXP',  kat:'usb',      vel:1, opis:'USB 2.0 socket EXP 1M'},
  {kod:'74286', naziv:'USB tip C punjač 3A EXP',             serija:'EXP',  kat:'usb',      vel:1, opis:'USB C 3A/5V~ EXP 1M'},
  {kod:'74285', naziv:'HDMI utičnica EXP',                   serija:'EXP',  kat:'hdmi',     vel:1, opis:'HDMI socket EXP 1M'},
  {kod:'74281', naziv:'Audio 2×RCA EXP',                     serija:'EXP',  kat:'audio',    vel:1, opis:'Audio 2×RCA EXP 1M'},
  {kod:'74282', naziv:'Audio/video BNC/BNC EXP',             serija:'EXP',  kat:'audio',    vel:1, opis:'BNC/BNC EXP 1M'},
  {kod:'74261', naziv:'Antenska TV IEC M/F EXP',             serija:'EXP',  kat:'antena',   vel:1, opis:'TV aerial IEC M/F EXP 1M'},
  {kod:'74262', naziv:'Antenska FM IEC F/F EXP',             serija:'EXP',  kat:'antena',   vel:1, opis:'FM aerial IEC F/F EXP 1M'},
  {kod:'74263', naziv:'Antenska TV završna 5dB EXP',         serija:'EXP',  kat:'antena',   vel:1, opis:'End-line 5dB EXP 1M'},
  {kod:'74264', naziv:'Antenska TV prolazna 10dB EXP',       serija:'EXP',  kat:'antena',   vel:1, opis:'Throughpass 10dB EXP 1M'},
  {kod:'74265', naziv:'SAT antenska F/F EXP',                serija:'EXP',  kat:'antena',   vel:1, opis:'TV/SAT F/F EXP 1M'},
  {kod:'74266', naziv:'TV/SAT završna EXP',                  serija:'EXP',  kat:'antena',   vel:1, opis:'TV/SAT aerial final EXP 1M'},
  {kod:'74211', naziv:'Telefon RJ12 6/4 Cat3 EXP',           serija:'EXP',  kat:'tel',      vel:1, opis:'Telephone RJ12 6/4 Cat3 EXP 1M'},
  {kod:'74212', naziv:'Telefon Keystone RJ12 EXP',           serija:'EXP',  kat:'tel',      vel:1, opis:'Keystone RJ12 6/4 EXP 1M'},
  {kod:'74201', naziv:'Keystone nosač EXP',                  serija:'EXP',  kat:'data',     vel:1, opis:'22,2mm, Keystone holder EXP'},
  {kod:'74221', naziv:'RJ45 Keystone Cat5e UTP EXP',         serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat5e UTP EXP 1M'},
  {kod:'74222', naziv:'RJ45 Keystone Cat5e FTP EXP',         serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat5e FTP EXP 1M'},
  {kod:'74223', naziv:'RJ45 Keystone Cat6 UTP EXP',          serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat6 UTP EXP 1M'},
  {kod:'74224', naziv:'RJ45 Keystone Cat6 FTP EXP',          serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat6 FTP EXP 1M'},
  {kod:'74225', naziv:'RJ45 Keystone Cat6A UTP EXP',         serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat6A UTP EXP 1M'},
  {kod:'74226', naziv:'RJ45 Keystone Cat6A FTP EXP',         serija:'EXP',  kat:'data',     vel:1, opis:'RJ45 Cat6A FTP EXP 1M'},
  {kod:'70001', naziv:'Slijepi modul EXP',                   serija:'EXP',  kat:'ostalo',   vel:1, opis:'Blank EXP 1M'},
],
};
